### ISSUE TITLE
Spanish characters.

### ISSUE THREAD

**Issue by ddares** [info-beamer/package-flap-display#1]
Hello, could Spanish characters be added to this package?

I need Ñ, ñ, á, é, í, ó, ú, basically.

Thank you.

**Comment by dividuum** [comment]
In theory yes, but this [image containing all the animations](https://github.com/info-beamer/package-flap-display/blob/master/letters.png) would have to be adjusted for that. I didn't create that, @MichaelKreil did. I don't think the code that generated the image is public.

**Comment by MichaelKreil** [comment]
The code is on GitHub of course: https://github.com/opendatacity/splitflap
/textures/1_generate_letters.js generates an image for each letter (with ImageMagick),
/textures/2_raytrace.js generates this animations sprite image.

**Comment by dividuum** [comment]
Oh. That's awesome. Thanks for the pointer. I'll take a quick look to see if I get this running. Thanks a lot.

**Comment by dividuum** [comment]
So it works but I'll still need to figure out a way to distribute the generated character images so the resulting image fills a texture of 2048x2048 max, as that's a hardware limit of the Pi. Right now the generated texture is <number of animation-steps> x <number of characters> which is 300x4880  for the example I generated.

**Comment by dividuum** [comment]
Done: https://github.com/info-beamer/package-flap-display/blob/master/refit.py

The package now includes a style for spanish output. Just update it and select the style on the config page.
