### ISSUE TITLE
README: Adding your own style

### ISSUE THREAD

**Issue by ls6** [info-beamer/package-flap-display#2]
The instructions on 'https://github.com/opendatacity/splitflap' for creating own style no longer work. Not only some Node.js commands got deprecated (easy fix), there is also some runtime issue — it is impossible to generate more that 21 letters.

It is probably sensible to remove this section from the README not to get an appetite too high.

P.S. I reached to the author on Twitter (because he doesn't seem to be associated with that repo anymore) — maybe he'll update the code.

**Comment by ls6** [comment]
Pinging @MichaelKreil here, maybe he's up for it 😄

**Comment by ls6** [comment]
Got a response from Michael (the author) on Twitter — he is too busy with other stuff to work on it. He's happy to pass it on, though.

**Comment by dividuum** [comment]
I just tried to run the scripts and it works for me. I'm using Ubuntu 18.04:

```
[sandboxed] dividuum@tau:~$ git clone https://github.com/opendatacity/splitflap
Cloning into 'splitflap'...
remote: Enumerating objects: 816, done.
remote: Total 816 (delta 0), reused 0 (delta 0), pack-reused 816
Receiving objects: 100% (816/816), 36.63 MiB | 4.62 MiB/s, done.
Resolving deltas: 100% (396/396), done.
[sandboxed] dividuum@tau:~$ cd splitflap/textures/
[sandboxed] dividuum@tau:~/splitflap/textures$ rm ../images/*
[sandboxed] dividuum@tau:~/splitflap/textures$ npm install
[...]
[sandboxed] dividuum@tau:~/splitflap/textures$ node 1_generate_letters.js 
Generating Font "400"
Generating Font "800"
Finished
[sandboxed] dividuum@tau:~/splitflap/textures$ node 2_raytrace.js 
Generating Font "400"
   Loading Letters
   Rendering Frame 1 von 15
[...]
   Saving Texture
Finished
[sandboxed] dividuum@tau:~/splitflap/textures$ ls -l ../images/
total 1984
-rw-rw-r-- 1 dividuum dividuum 197109 Nov  9 12:48 letters_400.png
-rw-rw-r-- 1 dividuum dividuum 179024 Nov  9 12:48 letters_800.png
-rw-rw-r-- 1 dividuum dividuum 843165 Nov  9 12:52 texture_400.png
-rw-rw-r-- 1 dividuum dividuum 803791 Nov  9 12:56 texture_800.png
[sandboxed] dividuum@tau:~/splitflap/textures$ npm -v
3.5.2
[sandboxed] dividuum@tau:~/splitflap/textures$ node -v
v8.10.0
[sandboxed] dividuum@tau:~/splitflap/textures$ 
```

What kind of problem are you running into?

**Comment by ls6** [comment]
I've tried running it with Node v12.12.0 (OS X) — this is probably the reason behind the issues.

First I got a bunch of errors becasue of deprecated use of "Buffer". Fixed those. Then I could only generate 21 letters with "1_generate_letters.js" — more would trigger an error when IM tried to "pop" to save.
I'm sorry for vague answers but that's all I remember and I deleted the setup already.

I'm happy to recreate the environment and provide more info if you want to dig deeper.

Meanwhile I'll try to use Node v8.10.0 like you did — I'm trying to generate a new set of letters for two reasons:
1) I'd like to see the numbers in reverse order so a countdown looks better. Now each step makes a cycle through all the characters.
2) I'd like to use Polish alphabet — I'm thinking about setting a board for our local Meetup when we meet in person.

BTW: thank you for the ability to run one device for free. Our free Meetup grew a lot (almost 3500 people) and it is increasingly difficult to run it at the scale with zero cash and volunteers only.

**Comment by ls6** [comment]
Hmmm… weird.

I've tried again and this time it worked. The "only" difference is that I have updated OS yesterday night.

So, it works with the exception of this warning:
`[DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

OSX Mojave (10.14.6) with Node v12.12.0 and npm 6.11.3
